import '~/globals.sass';
import Navigation from './Navigation';
import Footer from './Footer';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <Navigation />

                <main>{children}</main>

                <Footer />
            </body>
        </html>
    );
}
