'use client';

import Image from 'next/image';
import { ChangeEvent, FormEvent, useState } from 'react';

import o from '~/login/page.module.sass';

export default function Login() {
    const [twoFactorAuth, setTwoFactorAuth] = useState<boolean>(true);

    const handleLogin = async (event: any) => {
        event.preventDefault();
    };

    const handle2FA = async (event: any) => {
        event.preventDefault();
    };

    const handlePaste = (event: any) => {
        event.preventDefault();
        const firstInput = document.getElementById('1') as HTMLInputElement;

        const cpData = event.clipboardData?.getData('text');

        if (!firstInput || isNaN(parseInt(cpData ? cpData : ''))) return;

        for (let i = 0; i < (cpData?.length || 1); i++) {
            if (!document.getElementById(i.toString())) return console.log('not found');

            setTimeout(() => {
                (document.getElementById(i.toString()) as HTMLInputElement).value = cpData?.charAt(i) || '';

                if (!document.getElementById((i + 1).toString())) return;

                (document.getElementById((i + 1).toString()) as HTMLInputElement).focus();
            }, i * 150);
        }
    };

    const handleInput = (event: ChangeEvent) => document.getElementById((parseInt(event.target.id) + 1).toString())?.focus();

    return (
        <main>
            <title>Login — Nove</title>
            <section className={o.login}>
                {twoFactorAuth ? (
                    <div className={o.box}>
                        <Image src="/cdn/assets/logo.png" width={64} height={64} alt="Nove logo" />
                        <h1>Two factor authentication</h1>
                        <p>Provide code generated by your authenticator app.</p>
                        <form onSubmit={handle2FA} className={o.tfa}>
                            <input onChange={handleInput} onPaste={handlePaste} type="text" maxLength={1} id="0" />
                            <input onChange={handleInput} type="text" maxLength={1} id="1" />
                            <input onChange={handleInput} type="text" maxLength={1} id="2" />
                            <input onChange={handleInput} type="text" maxLength={1} id="3" />
                            <input onChange={handleInput} type="text" maxLength={1} id="4" />
                            <input type="text" maxLength={1} id="5" />
                        </form>
                    </div>
                ) : (
                    <div className={o.box}>
                        <Image src="/cdn/assets/logo.png" width={64} height={64} alt="Nove logo" />
                        <h1>Welcome back</h1>
                        <p>Login to your Nove account and get started.</p>
                        <form onSubmit={handleLogin}>
                            <label htmlFor="username">
                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 48 48">
                                    <path
                                        fill="currentColor"
                                        d="M 24 4 C 18.494917 4 14 8.494921 14 14 C 14 19.505079 18.494917 24 24 24 C 29.505083 24 34 19.505079 34 14 C 34 8.494921 29.505083 4 24 4 z M 12.5 28 C 10.032499 28 8 30.032499 8 32.5 L 8 33.699219 C 8 36.640082 9.8647133 39.277974 12.708984 41.091797 C 15.553256 42.90562 19.444841 44 24 44 C 28.555159 44 32.446744 42.90562 35.291016 41.091797 C 38.135287 39.277974 40 36.640082 40 33.699219 L 40 32.5 C 40 30.032499 37.967501 28 35.5 28 L 12.5 28 z"></path>
                                </svg>
                                <input type="text" id="username" placeholder="Username or e-mail" />
                            </label>
                            <label htmlFor="password">
                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 48 48">
                                    <path
                                        fill="currentColor"
                                        d="M30.5,5C23.596,5,18,10.596,18,17.5c0,1.149,0.168,2.257,0.458,3.314L5.439,33.833C5.158,34.114,5,34.496,5,34.894V41.5	C5,42.328,5.671,43,6.5,43h7c0.829,0,1.5-0.672,1.5-1.5V39h3.5c0.829,0,1.5-0.672,1.5-1.5V34h3.5c0.829,0,1.5-0.672,1.5-1.5v-3.788	C26.661,29.529,28.524,30,30.5,30C37.404,30,43,24.404,43,17.5S37.404,5,30.5,5z M32,19c-1.657,0-3-1.343-3-3s1.343-3,3-3	s3,1.343,3,3S33.657,19,32,19z"></path>
                                </svg>
                                <input type="password" id="password" placeholder="Password" />
                            </label>
                            <button type="submit">Login</button>
                        </form>
                    </div>
                )}
            </section>
        </main>
    );
}
